### ISSUE TITLE
RNA-Seq dataset suitable properties

### ISSUE THREAD

**Issue by JamalEH** [mgunady/yanagi#1]
Dear Team,
I read through the paper and found your tool, yanagi, very powerful and I'm excited to try it.

This is just a question rather than issue. I have an RNA-Seq dataset with the following characteristics:
1. paired-end
2. Unstranded
3. polyA+
4. read length : 75 bp
5. library depth: ranging from 23 to 33M reads (fragment) per library.
6. My RNA-seq is performed in 2 conditions (silencing vs control) in triplicate each.

My interest is to study alternative splicing changes upon the silencing experiment. In theory I want to check for SE, MXE, A5SS, A3SS, AF, AL, and diffrential polyadenylation site usage.

Can I apply yanagi on my dataset?

Thank you so much in advance!
Kind regards,
Jamal.

**Comment by mgunady** [comment]
Jamal,

Thanks for your interest in our tool yanagi. Yes that setting you described suites yanagi. You can use our pipeline to provide you PSI values for these types of AS events.
